
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IT Strategy - Stratégie TI
description: >-
    Workspace to develop an IT Strategy - Espace de travail pour développer une stratégie TI
baseurl: "/ITStrategy"
url: "https://sara-sabr.github.io/"

# Build settings
markdown: kramdown
theme: jekyll-theme-slate

# I18n
index:
  en:
  fr: index.html
language:
  en: English
  fr: Français
home:
  en: Home
  fr: Accueil
