
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IT Strategy - Stratégie TI
description: >-
    Workspace to develop an IT Strategy - Espace de travail pour développer une stratégie TI
index:
  en:
  fr: index.html
language:
  en: English
  fr: Français
home:
  en: Home
  fr: Accueil
home_link:
  en:
  fr: index
about:
  en: About
  fr: À propos
about_link:
  en: about.html
  fr: apropos.html
baseurl: "/ITStrategy"
url: "https://sara-sabr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author: SARA-SABR Team
# twitter_username: 
# github_username:  
# google_analytics: 

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
